### PR TITLE
Bump dependencies, bugfixes, expand the descriptions a bit

### PR DESCRIPTION
**Pull request by pacak**
I also added a test that tries to feed parsers more unusual values such as `--number=10` instead of `--number 10` and reports results I consider strange. Not used anywhere yet, probably worth going over the examples and checking if desired behavior can be achieved.

Also fixed CI while I'm it.

### CODE REVIEW

**Comment by epage** [comment]
This is a lot of different changes, each with their own aspects to discuss.  I've gone ahead and merged or did my own version of some of them.

Still remaining
- Testing
- Feature description

Please split these out (or maybe start with an issue)

**Comment by pacak** [comment]
There are only tests left here and at the moment they are just running and reporting stuff in the console. Probably makes sense combine with stuff described in #9. Not sure what is the best way to represent that. Any objections if I replace python runner with something rust based?

**Comment by epage** [comment]
If we add tests, I'd like them to be a bit more automated and fit within the existing practices of the project (e.g. python or Rust).

As for changing the runner, I'd recommend creating an issue on that so we can talk about what you are wanting to accomplish and requirements.  I try to share as much of this code between projects as possible.

... "cargo script" would be nice for this

**Comment by epage** [comment]
If this is just tests and they don't align with the project., I'm going to go ahead and close this.  Feel free to create an issue for further discussing testing needs

**Comment by pacak** [comment]
Those are tests the same way as detecting invalid utf8 is a test.
- does it support invalid utf8? Y/N
- does it support `--number=10` instead of `--number 10`?
- does it support `-vvv` instead of `-v -v -v`?
- does it detect unexpected flags?
- does it detect known but expected flags?
- does it support `-n10` instead of `-n 10`?

etc.

At least those things that can be tested automatically and they all affect end user experience about the same time or more as not supporting `OsString`. Obviously automatic, rendering some kind of table. But if having more columns with separate description is not an option - probably nothing to do here.

**Comment by epage** [comment]
> Those are tests the same way as detecting invalid utf8 is a test.

invalid utf8 is automated and follows the patterns and practices of this repo.  From what I could tell, these tests do not.

If we want to continue discussing this, please let's leave it to an issue.

**Pull request closed without merging**
